export enum message {
  notAuthorized = "You are not authorize to use this API.",
  tokenExpire = "Token got expire or token required",
  userNotFound = "user not found",
  passwordInvalid = "password is invalid",
  emailExists = "Email already exists",
  emailNotFound = "Email not found",
  passwordWeak = "Password is too weak",
  inValidCredentail = "Invalid credentials",
  roleNotFound = "Role not found",
  typeInValid = "Type is invalid",
  moduleNotFound = "Module not found",
  mailServiceNotEnable = "Mail service is not enabled",
  fcmServiceNotEnabled = "FCM service is not enabled",
  moduleAlreadyExists = "Module already exists with the name!",
}
